"""Jack Henry Symitar synthetic generator (HUG-162 revamp).

Reads the loan-product catalog from packages/synth-data/profiles/products.yaml.
Auto-Indirect loans receive a dealer_id. Credit Card loans skip amortization
here — their balances + transactions are generated by generators/cards.py.

Heavy math (amortization, delinquency, DPD bucketing) lives in
generators/symitar_amortize.py to keep this file under the structural cap.
"""

from datetime import UTC, datetime, timedelta
from decimal import Decimal
from typing import Any

import numpy as np

from synth_data.config import LoanProductSpec, ProductCatalog, SynthProfile
from synth_data.generators.dealers import (
    DealerRow,
    assign_dealer_id,
    dealer_reserve_for,
)
from synth_data.generators.lifecycle import generate_lifecycle_events
from synth_data.generators.officers import assign_officer_id, generate_officers
from synth_data.generators.origence import (
    ApplicationRow,
    ApprovalRow,
    FundingEventRow,
    OrigenceData,
)
from synth_data.generators.symitar_amortize import (
    balance_after,
    build_amortization,
    build_delinquency,
    loan_status_after,
    monthly_payment,
    months_elapsed,
    sample_loan_arrays,
)
from synth_data.generators.symitar_amortize import (
    dpd_bucket as _dpd_bucket,  # re-exported for tests
)
from synth_data.generators.symitar_standalone import generate_standalone_loans
from synth_data.generators.symitar_types import (
    BookedLoanRow,
    BranchRow,
    DelinquencySnapshotRow,
    LoanBalanceRow,
    PaymentRow,
    SymitarData,
)

__all__ = [
    "BRANCH_NAMES", "REGIONS", "PAYMENT_METHODS", "SymitarData",
    "_dpd_bucket", "generate_symitar_data",
]

BRANCH_NAMES = [
    "Main Branch", "North Branch", "South Branch", "East Branch", "West Branch",
    "Midtown Branch", "Westside Branch", "Eastside Branch",
    "Uptown Branch", "Downtown Branch",
]
REGIONS = ["Central", "North", "South", "East", "West"]
PAYMENT_METHODS = ["ach", "check", "online", "branch"]

_REF_DATE = datetime(2026, 4, 1, tzinfo=UTC)


def _build_card_loan(
    fe: FundingEventRow,
    app: ApplicationRow,
    appr: ApprovalRow,
    arrays: dict[str, Any],
    i: int,
) -> BookedLoanRow:
    """Credit-card 'loan' = the card itself; balances live in cards.py."""
    credit_limit = float(fe.funded_amount)
    rate = float(appr.rate) if appr.rate else 0.18
    originated_at = fe.funded_at + timedelta(days=int(arrays["orig_offset"][i]))
    # Cards don't mature; use a 30-year stub so the column stays non-null.
    maturity_at = originated_at + timedelta(days=365 * 30)
    return BookedLoanRow(
        loan_id=arrays["loan_uuids"][i], application_id=fe.application_id,
        branch_name=BRANCH_NAMES[int(arrays["branch_idxs"][i])],
        member_id=app.member_id, product_type_name=app.product_type_name,
        originated_at=originated_at,
        original_balance=Decimal(str(round(credit_limit, 2))),
        balance=Decimal("0.00"),
        rate=Decimal(str(round(rate, 4))),
        term_months=0,
        maturity_at=maturity_at, status="current",
        is_nonaccrual=False,
    )


_LoanResult = tuple[
    BookedLoanRow, list[LoanBalanceRow], list[PaymentRow],
    list[DelinquencySnapshotRow], int, int,
]


def _resolve_loan_terms(
    appr: ApprovalRow, spec: LoanProductSpec,
) -> tuple[int, float]:
    term = int(appr.term_months) if appr.term_months else (
        spec.term_months[0] if spec.term_months else 60
    )
    rate = float(appr.rate) if appr.rate else spec.rate_range[0]
    return term, rate


def _make_amortizing_loan_row(
    fe: FundingEventRow, app: ApplicationRow, arrays: dict[str, Any], i: int,
    term: int, rate: float, principal: float, status: str, ma: int, missed: int,
) -> BookedLoanRow:
    loan_id = arrays["loan_uuids"][i]
    _dpd = max(0, int(loan_id[0], 16) * 2 % 29 + (missed - 1) * 30 + 1) * bool(missed)
    cur_bal = (
        0.0 if status == "paid_off"
        else balance_after(principal, rate, term, ma)
    )
    originated_at = fe.funded_at + timedelta(days=int(arrays["orig_offset"][i]))
    return BookedLoanRow(
        loan_id=loan_id, application_id=fe.application_id,
        branch_name=BRANCH_NAMES[int(arrays["branch_idxs"][i])],
        member_id=app.member_id, product_type_name=app.product_type_name,
        originated_at=originated_at,
        original_balance=Decimal(str(round(principal, 2))),
        balance=Decimal(str(round(cur_bal, 2))),
        rate=Decimal(str(round(rate, 4))),
        term_months=term,
        maturity_at=originated_at + timedelta(days=term * 30),
        status=status,
        is_nonaccrual=(_dpd >= 90 or status == "charged_off"),
    )


def _build_amortizing_loan(
    fe: FundingEventRow,
    app: ApplicationRow,
    appr: ApprovalRow,
    profile: SynthProfile,
    spec: LoanProductSpec,
    arrays: dict[str, Any],
    i: int,
    bal_idx: int,
    delinq_idx: int,
) -> _LoanResult:
    term, rate = _resolve_loan_terms(appr, spec)
    principal = float(fe.funded_amount)
    pmt = monthly_payment(principal, rate, term)
    originated_at = fe.funded_at + timedelta(days=int(arrays["orig_offset"][i]))
    elapsed = months_elapsed(originated_at)
    status, ma = loan_status_after(
        float(arrays["status_r"][i]), profile.charge_off_rate,
        profile.dpd_30_rate, elapsed, term,
    )
    is_bad = status in ("delinquent", "charged_off")
    missed = int(arrays["delinq_starts"][i]) if is_bad else 0
    loan = _make_amortizing_loan_row(
        fe, app, arrays, i, term, rate, principal, status, ma, missed,
    )
    pm = PAYMENT_METHODS[int(arrays["pm_idxs"][i])]
    lb, p, bal_idx = build_amortization(
        loan.loan_id, originated_at, principal, rate, term, ma, pmt, missed,
        arrays["bal_pool"], arrays["pmt_pool"][i], bal_idx, pm,
    )
    drows: list[DelinquencySnapshotRow] = []
    if missed > 0:
        drows, delinq_idx = build_delinquency(
            loan.loan_id, originated_at, ma, missed,
            arrays["delinq_pool"], delinq_idx,
        )
    return loan, lb, p, drows, bal_idx, delinq_idx


def _build_loan(
    fe: FundingEventRow,
    app: ApplicationRow,
    appr: ApprovalRow,
    profile: SynthProfile,
    spec_by_code: dict[str, LoanProductSpec],
    arrays: dict[str, Any],
    i: int,
    bal_idx: int,
    delinq_idx: int,
) -> _LoanResult:
    spec = spec_by_code[app.product_type_name]
    if spec.code == "credit_card":
        card_loan = _build_card_loan(fe, app, appr, arrays, i)
        return card_loan, [], [], [], bal_idx, delinq_idx
    return _build_amortizing_loan(
        fe, app, appr, profile, spec, arrays, i, bal_idx, delinq_idx,
    )


def _attach_dealers(
    loans: list[BookedLoanRow],
    dealers: list[DealerRow],
    seed: int,
) -> None:
    if not dealers:
        return
    rng = np.random.default_rng(seed + 65)
    dealer_by_id = {d.dealer_id: d for d in dealers}
    for loan in loans:
        if loan.product_type_name == "auto_indirect":
            d_id = assign_dealer_id(rng, dealers)
            loan.dealer_id = d_id
            loan.dealer_reserve_amount = dealer_reserve_for(
                rng, loan.original_balance, dealer_by_id[d_id].markup_tier,
            )


def _build_branches(profile: SynthProfile) -> list[BranchRow]:
    return [
        BranchRow(branch_name=BRANCH_NAMES[i], region=REGIONS[i % len(REGIONS)])
        for i in range(profile.branch_count)
    ]


def generate_symitar_data(
    origence: OrigenceData,
    profile: SynthProfile,
    catalog: ProductCatalog,
    dealers: list[DealerRow] | None = None,
) -> SymitarData:
    rng = np.random.default_rng(profile.seed + 1)
    branches = _build_branches(profile)
    funded = origence.funding_events
    if not funded:
        return SymitarData(
            branches=branches, booked_loans=[], loan_balances=[],
            payments=[], delinquency_snapshots=[],
        )
    spec_by_code = {p.code: p for p in catalog.loan_products}
    arrays = sample_loan_arrays(
        rng, len(funded), profile.branch_count, len(PAYMENT_METHODS),
    )
    app_map = {a.application_id: a for a in origence.applications}
    appr_map = {a.application_id: a for a in origence.approvals}
    booked: list[BookedLoanRow] = []
    bals: list[LoanBalanceRow] = []
    pmts: list[PaymentRow] = []
    drows: list[DelinquencySnapshotRow] = []
    bal_idx = delinq_idx = 0
    for i, fe in enumerate(funded):
        loan, lb, p, d, bal_idx, delinq_idx = _build_loan(
            fe, app_map[fe.application_id], appr_map[fe.application_id],
            profile, spec_by_code, arrays, i, bal_idx, delinq_idx,
        )
        booked.append(loan)
        bals.extend(lb)
        pmts.extend(p)
        drows.extend(d)
    member_pool = [a.member_id for a in origence.applications if a.status == "funded"]
    standalone = generate_standalone_loans(
        rng, profile.standalone_loan_count, member_pool, catalog, branches,
    )
    officers = generate_officers(profile, [b.branch_name for b in branches])
    all_loans = booked + standalone
    for loan in all_loans:
        loan.officer_id = assign_officer_id(loan.loan_id, loan.branch_name, officers)
    if dealers:
        _attach_dealers(all_loans, dealers, profile.seed)
    return SymitarData(
        branches=branches, booked_loans=all_loans, loan_balances=bals,
        payments=pmts, delinquency_snapshots=drows, officers=officers,
        loan_lifecycle_events=generate_lifecycle_events(all_loans, profile.seed),
    )
